version: 2
registries:
  dhi-dockerhub:
    type: docker-registry
    url: dhi.io
    username: ${{secrets.DOCKERHUB_USERNAME}}
    password: ${{secrets.DOCKERHUB_TOKEN}}

updates:
  # Maintain Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "buildplan"
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "chore(deps):"

  # Maintain Dockerfile dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - dhi-dockerhub
    assignees:
      - "buildplan"
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "chore(deps):"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "buildplan"
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "chore(deps):"
