module.exports = {
  vpnHostingProviders: {
    // HIGH: Dedicated VPN Companies, Proxy Providers, and Bulletproof/Offshore Hosting
    high: [
      // Commercial VPNs & Parent Companies
      "M247",
      "Datacamp",
      "DataPacket",
      "London Trust Media",
      "Kape Technologies",
      /* NordVPN Parent */
      "Tefincom",
      "Amagicom",
      /* Mullvad Parent */
      "Golden Frog",
      /* VyprVPN Parent */
      "Mudhook",
      "Proton",
      "Mullvad",
      "NordVPN",
      "Surfshark",
      "ExpressVPN",
      "CyberGhost",
      "Windscribe",
      "TunnelBear",
      "ZenMate",
      "Private Internet Access",
      "HideMyAss",
      "Perfect Privacy",
      "AirVPN",
      "TorGuard",
      "Ivacy",
      "PureVPN",

      // Proxy Networks & Bulletproof/Offshore Hosting
      "31173 Services",
      "Owl Limited",
      "PacketHub",
      "Hydra Communications",
      "Strong Technology",
      "Powerhouse Management",
      "QuadraNet",
      "Psychz",
      "ColoCrossing",
      "NFOrce",
      "i3D.net",
      "Melbicom",
      "Green Floid",
      "LogicWeb",
      "Creanova",
      "EstNOC",
      "Ip-Only",
      "GSL Networks",
      "Tzulo",
      "ReliableSite",
      "Feral Hosting",
      "Spine Telecom",
      "Anexia",
      "HostRoyale",
      "Keminet",
      "Cablenet Communications",
      "NovoServe",
      "Leaseweb",
      "DataCamp Limited",
      "Heficed",
      "HostHatch",
      "FranTech",
      "PONYNET",
      "BuyVM",
      "Performive",
      "G-Core Labs",
      "M247 Europe",
      "Unmanaged Ltd",
      "DMZHOST",
      "Techoff",

      // Specific High Risk / Proxy Providers
      "Digital Energy Technologies",
      "Stark Industries",
      "Web Horizon",
      "Misaka",
      "AEZA",
      "XTom",
      "TerraHost",
      "ServerAstra",
      "HostKey",
      "Inferno Solutions",
      "Lawrenceville Plasma Physics",
      "UAB Cherry Servers",
      "Veesp",
      "PQ Hosting",
      "Zappie Host",
      "FlokiNET",
      "Njalla",
      "1984 Group",
      "BlazingFast",
      "Offshore Racks",
      "Quasi Networks",
      "Virtual Systems",
      "Snel.com",
      "Hostwinds",
    ],

    // MEDIUM: Budget/Offshore VPS (Often abused for VPNs/Seedboxes, but distinct from Major Clouds)
    medium: [
      "Zenlayer",
      "Cogent",
      "Clouvider",
      "Nexeon",
      "Limestone",
      "Hivelocity",
      "Nexus Bytes",
      "Glesys",
      "Host Universal",
      "Latitude.sh",
      "Contabo",
      "Netcup",
      "HostEONS",
      "DataWagon",
      "G-Core",
      "Gcore",
      "Selectel",
      "UpCloud",
      "Time4VPS",
      "Pfcloud",
      "H4Y Technologies",
      "Driftnet",
      "Kamatera",
      "GreenCloud",
      "RackNerd",
      "CrownCloud",
      "Virmach",
      "Sharktech",
      "Wholesale Internet",
      "Nocix",
      "FDCServers",
      "VolumeDrive",
      "Alwyzon",
      "LunaNode",
      "AlexHost",
      "KnownHost",
      "CloudCone",
      "HostPapa",
    ],

    // LOW: Major Clouds, CDNs & Enterprise Infrastructure (Safe Datacenters, NOT Residential)
    low: [
      // Big Cloud
      "Amazon",
      "AWS",
      "Google",
      "Google Cloud",
      "Microsoft",
      "Azure",
      "Oracle",
      "Oracle Cloud",
      "Alibaba",
      "Aliyun",
      "Tencent",
      "Tencent Cloud",
      "Huawei",
      "Huawei Cloud",
      "Baidu",
      "IBM",
      "IBM Cloud",
      "SoftLayer",
      "Rackspace",
      "Salesforce",
      "SAP",
      // Tier 1 Enterprise
      "Cisco",
      "Hetzner",
      "OVH",
      "OVHcloud",
      "Linode",
      "Akamai",
      "DigitalOcean",
      "Vultr",
      "Scaleway",
      "Equinix",
      "Equinix Metal",
      "Leaseweb",
      "Servers.com",
      "Choopa",
      "The Constant Company",
      "Cloudflare",
      "Fastly",
      "Edgio",
      "Limelight",
      "EdgeCast",
      "CDN77",
      "BunnyCDN",
      // CDNs & EDGE Nets
      "Imperva",
      "Incapsula",
      "Sucuri",
      "StackPath",
      "KeyCDN",
      "CacheFly",
      // PAAS, App Hosts & E-Commerce
      "Fly.io",
      "Heroku",
      "Netlify",
      "Vercel",
      "Render",
      "Railway",
      "DigitalOcean App Platform",
      "Automattic",
      "Shopify",
      "Squarespace",
      "Wix",
      "HubSpot",
      "BigCommerce",
      // MASS Web Hosts
      "WP Engine",
      "Kinsta",
      "Pantheon",
      "GoDaddy",
      "Bluehost",
      "HostGator",
      "DreamHost",
      "IONOS",
      "1&1",
      "Strato",
      "Hostinger",
      "SiteGround",
      "Namecheap",
      "InMotion",
      "A2 Hosting",
      "InterServer",
      "Liquid Web",
      "Aruba",
      "Gandi",

      // --- REGIONAL ---
      // Japan
      "Sakura Internet",
      "GMO Internet",
      // Korea
      "Naver Cloud",
      "Kakao Corp",
      // Russia/CIS
      "Yandex",
      "Selectel",
      "VK Cloud",
      "Mail.Ru",
      // China (Tier 2)
      "Kingsoft",
      "JD Cloud",
      "UCloud",
      // Brazil / LATAM
      "UOL",
      "Locaweb",
      // India
      "Tata Communications",
    ],
  },

  // High-Risk ASNs strictly associated with VPNs and Proxies
  vpnASNs: [
    "AS60729",
    "AS4224",
    "AS396507",
    "AS200651",
    "AS1921",
    "AS202425",
    "AS9009",
    "AS39351",
    "AS212238",
    "AS60068",
    "AS216025",
    "AS208172",
    "AS136787",
    "AS147049",
    "AS207137",
    "AS141039",
    "AS204957",
    "AS47583",
    "AS53667",
    "AS25369",
    "AS62651",
    "AS22363",
    "AS56655",
    "AS200019",
    "AS11878",
    "AS203020",
    "AS210644",
    "AS44477",
    "AS57523",
    "AS213896",
    "AS49981",
    "AS397423",
    "AS136787",
    "AS39087",
    "AS200069",
    "AS205988",
    "AS208323",
    "AS51852",
    "AS49581",
    "AS62744",
  ],
};
